spring:
  mvc:
    log-resolved-exception: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    database-change-log-lock-table: _liquibase_changelog_lock
    database-change-log-table: _liquibase_changelog
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    time-zone: Europe/Warsaw
  cache:
    jcache:
      config: classpath:cache/ehcache.cfg.xml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  mail:
    host: ${AHMS_MAIL_HOST:127.0.0.1}
    properties:
      smtp:
        starttls:
          required: ${AHMS_MAIL_SSL_ENABLED:false}
      mail:
        smtp:
          ssl:
            enabled: ${AHMS_MAIL_SSL_ENABLED:false}
          auth: ${AHMS_MAIL_AUTH_ENABLED:false}
          starttls:
            enabled: ${AHMS_MAIL_SSL_ENABLED:false}

application:
  app-name: AirHubMaster
  i18n:
    available-languages:
      - en
      - pl
    default-langauge: pl
    bundles:
      - i18n-api/messages
      - i18n-mail/messages
      - i18n-jpa/messages
  mail:
    templates-dir: classpath:/templates
    send-email-address: ${AHMS_MAIL_SEND_ADDRESS:noreply@ahms.miloszgilga.pl}
    reply-email-address: ${AHMS_MAIL_REPLY_ADDRESS:info@ahms.miloszgilga.pl}
  jwt:
    issuer: airhubmaster
    secret: ${AHMS_JWT_SECRET:supersecret}
    access-expired-sec: 300 # 5 minutes
    refresh-expired-sec: 2629800 # 1 month
  ota:
    register-expired-sec: 172800 # 2 days
    renew-password-expired-sec: 6000 # 10 minutes
    length: 10
