#
# Copyright (c) 2023 by MILOSZ GILGA <http://miloszgilga.pl>
#
# File name: libs.versions.toml
# Last modified: 13/05/2023, 19:16
# Project name: air-hub-master-server
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License. You may obtain a copy of the License at
#
#     <http://www.apache.org/license/LICENSE-2.0>
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the license.
#

# libs.versions.toml

[versions]
springBoot          = '3.0.6'
liquibase           = '4.19.0'
lombok              = '1.18.26'
h2Driver            = '2.1.214'
mysqlDriver         = '8.0.31'
jjwt                = '0.11.5'
ehCache             = '3.10.8'
jaxb                = '2.3.1'
openApi             = '2.1.0'
jmpsl               = '1.0.2_05'
commonsText         = '1.10.0'
commonsIO           = '2.13.0'
freemarker          = '2.3.32'

springBootDep       = '1.0.15.RELEASE'
dotenvGradle        = '2.0.0'
sshGradle           = '2.11.2'

[libraries]
spring-boot-starter-web             = { module = 'org.springframework.boot:spring-boot-starter-web',                version.ref = 'springBoot' }
spring-boot-starter-cache           = { module = 'org.springframework.boot:spring-boot-starter-cache',              version.ref = 'springBoot' }
spring-boot-starter-security        = { module = 'org.springframework.boot:spring-boot-starter-security',           version.ref = 'springBoot' }
spring-boot-starter-data-jpa        = { module = 'org.springframework.boot:spring-boot-starter-data-jpa',           version.ref = 'springBoot' }
spring-boot-starter-validation      = { module = 'org.springframework.boot:spring-boot-starter-validation',         version.ref = 'springBoot' }
spring-boot-starter-test            = { module = 'org.springframework.boot:spring-boot-starter-test',               version.ref = 'springBoot' }
spring-boot-starter-mail            = { module = 'org.springframework.boot:spring-boot-starter-mail',               version.ref = 'springBoot' }
spring-boot-devtools                = { module = 'org.springframework.boot:spring-boot-devtools',                   version.ref = 'springBoot' }
spring-boot-config-processor        = { module = 'org.springframework.boot:spring-boot-configuration-processor',    version.ref = 'springBoot' }
liquibase                           = { module = 'org.liquibase:liquibase-core',                                    version.ref = 'liquibase' }
h2-driver                           = { module = 'com.h2database:h2',                                               version.ref = 'h2Driver' }
mysql-driver                        = { module = 'mysql:mysql-connector-java',                                      version.ref = 'mysqlDriver' }
lombok                              = { module = 'org.projectlombok:lombok',                                        version.ref = 'lombok' }
jjwt-api                            = { module = 'io.jsonwebtoken:jjwt-api',                                        version.ref = 'jjwt' }
jjwt-impl                           = { module = 'io.jsonwebtoken:jjwt-impl',                                       version.ref = 'jjwt' }
jjwt-jackson                        = { module = 'io.jsonwebtoken:jjwt-jackson',                                    version.ref = 'jjwt' }
ehcache                             = { module = 'org.ehcache:ehcache',                                             version.ref = 'ehCache' }
jaxb-api                            = { module = 'javax.xml.bind:jaxb-api',                                         version.ref = 'jaxb' }
jaxb-impl                           = { module = 'com.sun.xml.bind:jaxb-impl',                                      version.ref = 'jaxb' }
openapi-webmvc-starter              = { module = 'org.springdoc:springdoc-openapi-starter-webmvc-ui',               version.ref = 'openApi' }
jmpsl-core                          = { module = 'pl.miloszgilga:jmpsl-core',                                       version.ref = 'jmpsl' }
jmpsl-security                      = { module = 'pl.miloszgilga:jmpsl-security',                                   version.ref = 'jmpsl' }
jmpsl-communication                 = { module = 'pl.miloszgilga:jmpsl-communication',                              version.ref = 'jmpsl' }
commons-text                        = { module = 'org.apache.commons:commons-text',                                 version.ref = 'commonsText' }
commons-io                          = { module = 'commons-io:commons-io',                                           version.ref = 'commonsIO' }
freemarker                          = { module = 'org.freemarker:freemarker',                                       version.ref = 'freemarker' }

[plugins]
spring-boot-plugin                  = { id     = 'org.springframework.boot',                                        version.ref = 'springBoot' }
spring-dept-plugin                  = { id     = 'io.spring.dependency-management',                                 version.ref = 'springBootDep' }
dotenv-gradle                       = { id     = 'co.uzzu.dotenv.gradle',                                           version.ref = 'dotenvGradle' }
ssh-gradle                          = { id     = 'org.hidetake.ssh',                                                version.ref = 'sshGradle' }
